apiVersion: apps/v1
kind: Deployment
metadata:
name: blog-deployment
spec:
replicas: 1
selector:
matchLabels:
app: blog
template:
metadata:
labels:
app: blog
spec:
containers:
- name: blog-container
image: rachita06/blogimg01:v1
ports:
- containerPort: 80
