apiVersion: apps/v1
kind: Deployment
metadata:
  name: devops-proj
  namespace: dev
spec:
  replicas: 1
  selector:
    matchLabels:
      app: devops-proj
  template:
    metadata:
      labels:
        app: devops-proj
    spec:
      containers:
      - name: devops-proj
        image: rachita06/devops-proj:v1   # Docker Hub image
        ports:
        - containerPort: 80
